version: 2
jobs:
   build:
     docker:
       - image: base/archlinux
     steps:
       - checkout
       - run:
           name: Install build dependencies
           command: pacman -Syu && pacman -S --noconfirm cmake ninja libx11 python2 git
       - run:
           name: Enable python2
           command: mkdir -p /tmp/python_for_libwebrtc_build && ln -s /usr/bin/python2 /tmp/python_for_libwebrtc_build/python
       - run:
           name: Run cmake
           command: PATH=/tmp/python_for_libwebrtc_build:$PATH cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DWEBRTC_BRANCH_HEAD=refs/branch-heads/67 .
       - run:
           name: Build
           command: PATH=/tmp/python_for_libwebrtc_build:$PATH ninja package
       - run:
           name: Move artifacts
           command: mv libwebrtc-*.tar.gz $CIRCLE_ARTIFACTS/
